### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by helish88** [uburuntu/rawg#2]
![image](https://user-images.githubusercontent.com/52331802/76562398-fcb40f00-64ad-11ea-99ee-8d6c441a3bb6.png)

**Comment by uburuntu** [comment]
Hi! Yep, this lib is out of date 😞 
Rawg released brand new API, so I've given up support so far.

**Comment by uburuntu** [comment]
@helish88 hi again. I've update lib for new api, you can try it.

**Comment by helish88** [comment]
ok,thx
